CREATE TABLE IF NOT EXISTS `EShop`.`Customers`(
    `id` INT(11) NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(255) NOT NULL,
    `orderId` INT(11) NOT NULL,
    PRIMARY KEY (`id`)
)
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8